# Generated by Django 6.0.3 on 2026-03-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.city'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.city'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_status_en',
            field=models.CharField(choices=[('свободный', 'свободный'), ('забронированный', 'забронированный'), ('занят', 'занят')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_status_ru',
            field=models.CharField(choices=[('свободный', 'свободный'), ('забронированный', 'забронированный'), ('занят', 'занят')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_en',
            field=models.CharField(choices=[('люкс', 'люкс'), ('полулюкс', 'полулюкс'), ('стандарт', 'стандарт'), ('эконом', 'эконом'), ('семейный', 'семейный')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_ru',
            field=models.CharField(choices=[('люкс', 'люкс'), ('полулюкс', 'полулюкс'), ('стандарт', 'стандарт'), ('эконом', 'эконом'), ('семейный', 'семейный')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
