# Generated by Django 6.0.3 on 2026-03-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_alter_booking_hotel_alter_booking_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_guest',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
