# Generated by Django 6.0.3 on 2026-03-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
